fitts/urls.py
from django.urls import path
from . import views

app_name = 'fitts'

urlpatterns = [
    path('', views.login, name='login'),
    path('fitts_task/1', views.fitts1, name='fitts1'),
    path('fitts_task/2', views.fitts2, name='fitts2'),
    path('fitts_task/3', views.fitts3, name='fitts3'),
    path('fitts_task/4', views.fitts4, name='fitts4'),
    path('fitts_task/5', views.fitts5, name='fitts5'),
    path('fitts_task/6', views.fitts6, name='fitts6'),
    path('fitts_task/end', views.end, name='end')
]

mole/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('fitts.urls')),
]

whack_a_mole/game/urls.py
from django.urls import path
from . import views

app_name = 'game'

urlpatterns = [
    path('', views.home, name='home'),
    path('game/<int:pk>', views.game, name='game'),
]

whack_a_mole/whack_a_mole/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('game.urls')),
]

fitts/models.py
from django.db import models

# Create your models here.

# class Users(models.Model):
#     name = models.CharField(max_length = 200)
#     age = models.IntegerField(default = 0)

#     def __str__(self):
#         return self.name

class Tasks(models.Model):
    age = models.IntegerField(default = 0)
    email = models.CharField(max_length = 200)
    transform = models.CharField(max_length = 200)
    distance = models.FloatField()
    time = models.FloatField()

whack_a_mole/game/models.py
from django.db import models

# Create your models here.


class Result(models.Model):
    age = models.IntegerField(default=0)
    score = models.IntegerField(default=0)

fitts/views.py
from django.shortcuts import render, redirect
from .models import Tasks
from django.urls import reverse

# Create your views here.

def login(request):
    if request.method == "POST":
        email = request.POST.get('email')
        age = request.POST.get('age')
        request.session['email']=email
        request.session['age']=age
        return redirect('fitts:fitts1')
    elif request.method == "GET":
        return render(request, 'fitts/login.html')

def fitts1(request):
    if request.method == "POST":
        for i in range(1, 9):
            age = request.session.get('age', None)
            email = request.session.get('email', None)
            transform = request.POST.get('transform', None)
            distance = request.POST.get('distance' + str(i), None)
            time = request.POST.get('time' + str(i), None)
            Tasks.objects.create(
                age = age,
                email = email,
                transform = transform,
                distance = distance,
                time = time
            )
        return redirect('fitts:fitts2')
    elif request.method == "GET":
        return render(request, 'fitts/fittstask1.html',{})

def fitts2(request):
    if request.method == "POST":
        for i in range(1, 9):
            age = request.session.get('age')
            email = request.session.get('email')
            transform = request.POST.get('transform', None)
            distance = request.POST.get('distance' + str(i), None)
            time = request.POST.get('time' + str(i), None)
            Tasks.objects.create(
                age = age,
                email = email,
                transform = transform,
                distance = distance,
                time = time
            )
        return redirect('fitts:fitts3')
    elif request.method == "GET":
        return render(request, 'fitts/fittstask2.html',{})

def fitts3(request):
    if request.method == "POST":
        for i in range(1, 9):
            age = request.session.get('age')
            email = request.session.get('email')
            transform = request.POST.get('transform', None)
            distance = request.POST.get('distance' + str(i), None)
            time = request.POST.get('time' + str(i), None)
            Tasks.objects.create(
                age = age,
                email = email,
                transform = transform,
                distance = distance,
                time = time
            )
        return redirect('fitts:fitts4')
    elif request.method == "GET":
        return render(request, 'fitts/fittstask3.html',{})

def fitts4(request):
    if request.method == "POST":
        for i in range(1, 9):
            age = request.session.get('age')
            email = request.session.get('email')
            transform = request.POST.get('transform', None)
            distance = request.POST.get('distance' + str(i), None)
            time = request.POST.get('time' + str(i), None)
            Tasks.objects.create(
                age = age,
                email = email,
                transform = transform,
                distance = distance,
                time = time
            )
        return redirect('fitts:fitts5')
    elif request.method == "GET":
        return render(request, 'fitts/fittstask4.html',{})

def fitts5(request):
    if request.method == "POST":
        for i in range(1, 9):
            age = request.session.get('age')
            email = request.session.get('email')
            transform = request.POST.get('transform', None)
            distance = request.POST.get('distance' + str(i), None)
            time = request.POST.get('time' + str(i), None)
            Tasks.objects.create(
                age = age,
                email = email,
                transform = transform,
                distance = distance,
                time = time
            )
        return redirect('fitts:fitts6')
    elif request.method == "GET":
        return render(request, 'fitts/fittstask5.html',{})

def fitts6(request):
    if request.method == "POST":
        for i in range(1, 9):
            age = request.session.get('age')
            email = request.session.get('email')
            transform = request.POST.get('transform', None)
            distance = request.POST.get('distance' + str(i), None)
            time = request.POST.get('time' + str(i), None)
            Tasks.objects.create(
                age = age,
                email = email,
                transform = transform,
                distance = distance,
                time = time
            )
        return redirect('fitts:end')
    elif request.method == "GET":
        return render(request, 'fitts/fittstask6.html',{})

def end(request):
    return render(request, 'fitts/end.html')

whack_a_mole/game/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .models import Result

# Create your views here.


def home(request):
    if request.method == "GET":
        return render(request, 'game/home.html')
    elif request.method == "POST":
        age = request.POST.get('age')
        pk = 0
        if age == "ten":
            pk = 0
        elif age == "thirty":
            pk = 1
        elif age == "fifty":
            pk = 2
        request.session['age'] = pk
        return redirect('game:game', pk=pk)


def game(request, pk):
    if request.method == "GET":
        data = {
            'pk': pk,
            'mu': 9.2,
        }
        return render(request, 'game/game.html', data)
    elif request.method == "POST":
        age = request.session.get('age')
        score = request.POST.get('score')
        Result.objects.create(
            age=age,
            score=score
        )
        return redirect('game:game', pk=pk)

fitts/templates/fitts/end.html
<html>
<div>
    <p>설문에 참여해주셔서 감사합니다.
    </p>
</div>

</html>

fitts/templates/fitts/fittstask.html
<html>

<head>
    <script src="https://d3js.org/d3.v4.min.js"></script>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css">
</head>

<body>

    <style>

    </style>
    <form id="frm" action="{% url 'fitts:fitts' %}" method="POST" style="display: none;">
        {% csrf_token %}
        <input type="text" id="tfrm" name="transform">
        <input type="number" step="any" id="dt1" name="distance1">
        <input type="number" id="tm1" name="time1">
        <input type="number" step="any" id="dt2" name="distance2">
        <input type="number" id="tm2" name="time2">
        <input type="number" step="any" id="dt3" name="distance3">
        <input type="number" id="tm3" name="time3">
        <input type="number" step="any" id="dt4" name="distance4">
        <input type="number" id="tm4" name="time4">
        <input type="number" step="any" id="dt5" name="distance5">
        <input type="number" id="tm5" name="time5">
        <input type="number" step="any" id="dt6" name="distance6">
        <input type="number" id="tm6" name="time6">
        <input type="number" step="any" id="dt7" name="distance7">
        <input type="number" id="tm7" name="time7">
        <input type="number" step="any" id="dt8" name="distance8">
        <input type="number" id="tm8" name="time8">
        <input type="submit" id="sm">
    </form>
    <script>

        var transform = 1;
        var xcoordinateArray = [];
        var ycoordinateArray = [];
        var timeArry = [];
        var totalTime = [];
        var distance = [];
        var totalDistance = 0;
        var index = 0;
        var fillingColor;
        var dist = 100;
        var width = 20;
        var dist2 = 150;
        var dist3 = 200;
        var width2 = 30;
        var dataVals = [[0.698132, "1"], [1.39626, "8"], [2.0944, "6"], [2.79253, "4"], [3.49066, "2"], [4.18879, "9"], [4.88692, "7"], [5.58505, "5"], [6.28319, "3"]];

        var page = d3.select("body").append("svg");
        page.attr("width", 600).attr("height", 600)
            .style("border", "4px solid black");

        var circles = page.selectAll("circle")
            .data(dataVals)
            .enter()
            .append("circle");

        var circleGroup = circles.attr("cx", function (d, i) { return 300 + dist * Math.cos(d[0]); })
            .attr("cy", function (d, i) { return 300 + dist * Math.sin(d[0]); })
            .attr("r", width)
            .attr("id", function (d, i) { return d[1]; })
            //.on("mouseover",handleMouseOver)
            //.on("mouseout", handleMouseOut)
            .attr("stroke", "black")
            .style("fill", function (d, i) {
                if (d[1] == "1")
                    fillingColor = "black";
                else
                    fillingColor = "red";
                return fillingColor
            });

        circleGroup.on("click", clickCircle);

        var button = d3.select("body")
            .append("input")
            .attr("type", "button")
            .attr("name", "DistanceVsTime")
            .attr("value", "결과제출하기")
            .on("click", function (d) {
                for (var i = 1; i < 9; i++) {
                    var xSquare = (xcoordinateArray[i + 1] - xcoordinateArray[i]) * (xcoordinateArray[i + 1] - xcoordinateArray[i]);
                    var ySquare = (ycoordinateArray[i + 1] - ycoordinateArray[i]) * (ycoordinateArray[i + 1] - ycoordinateArray[i]);
                    distance[i] = Math.sqrt(xSquare + ySquare);
                    totalTime[i] = timeArry[i + 1] - timeArry[i];
                }
                for (var i = 1; i < 9; i++) {
                    totalDistance = +distance[i];
                }
                //document.getElementById("textBox").innerHTML=totalDistance;
                for (var i = 1; i < 10; i++) {
                    var tab = document.getElementById("Distancedata");
                    var row = tab.insertRow(0);
                    var cell1 = row.insertCell(0);
                    var cell2 = row.insertCell(1);

                    if (i == 9) {
                        cell1.innerHTML = "DistanceBetweenNodes";
                        cell2.innerHTML = "Time(in ms)";
                    }
                    else {
                        cell1.innerHTML = distance[i];
                        cell2.innerHTML = totalTime[i];
                        id_dt = "dt" + i
                        id_tm = "tm" + i
                        console.log(id_dt)
                        console.log(id_tm)
                        document.getElementById(id_dt).setAttribute('value', parseFloat(distance[i]));
                        document.getElementById(id_tm).setAttribute('value', parseFloat(totalTime[i]));
                        document.getElementById('tfrm').setAttribute('value', transform);
                        console.log(distance[i])
                        console.log(totalTime[i])
                        console.log(transform)
                    }
                }
                document.getElementById('sm').click();
            });


        var button2 = d3.select("body")
            .append("input")
            .attr("type", "button")
            .attr("name", "Transform2")
            .attr("value", "Transform2")
            .on("click", function (d) {
                index = 0;
                transform = 2;
                page.selectAll("circle").remove();

                //var radius=document.getElementById("radius").value;
                //var amplitude=document.getElementById("Amplitude").value;
                page.selectAll("circle")
                    .data(dataVals)
                    .enter()
                    .append("circle")
                    .attr("cx", function (d, i) { return 300 + dist2 * Math.cos(d[0]); })
                    .attr("cy", function (d, i) { return 300 + dist2 * Math.sin(d[0]); })
                    .attr("r", width)
                    .attr("id", function (d, i) { test = d[1]; return d[1]; })
                    .style("fill", function (d, i) { var fillingcolor; if (d[1] == "1") fillingcolor = "black"; else fillingcolor = "red"; return fillingcolor })
                    .on("click", clickCircle);

            });
        var button3 = d3.select("body")
            .append("input")
            .attr("type", "button")
            .attr("name", "Transform3")
            .attr("value", "Transform3")
            .on("click", function (d) {
                index = 0;
                transform = 3;
                page.selectAll("circle").remove();

                //var radius=document.getElementById("radius").value;
                //var amplitude=document.getElementById("Amplitude").value;
                page.selectAll("circle")
                    .data(dataVals)
                    .enter()
                    .append("circle")
                    .attr("cx", function (d, i) { return 300 + dist3 * Math.cos(d[0]); })
                    .attr("cy", function (d, i) { return 300 + dist3 * Math.sin(d[0]); })
                    .attr("r", width)
                    .attr("id", function (d, i) { test = d[1]; return d[1]; })
                    .style("fill", function (d, i) { var fillingcolor; if (d[1] == "1") fillingcolor = "black"; else fillingcolor = "red"; return fillingcolor })
                    .on("click", clickCircle);

            });

        var button4 = d3.select("body")
            .append("input")
            .attr("type", "button")
            .attr("name", "Transform4")
            .attr("value", "Transform4")
            .on("click", function (d) {
                index = 0;
                transform = 4;
                page.selectAll("circle").remove();

                //var radius=document.getElementById("radius").value;
                //var amplitude=document.getElementById("Amplitude").value;
                page.selectAll("circle")
                    .data(dataVals)
                    .enter()
                    .append("circle")
                    .attr("cx", function (d, i) { return 300 + dist * Math.cos(d[0]); })
                    .attr("cy", function (d, i) { return 300 + dist * Math.sin(d[0]); })
                    .attr("r", width2)
                    .attr("id", function (d, i) { test = d[1]; return d[1]; })
                    .style("fill", function (d, i) { var fillingcolor; if (d[1] == "1") fillingcolor = "black"; else fillingcolor = "red"; return fillingcolor })
                    .on("click", clickCircle);

            });

        var button5 = d3.select("body")
            .append("input")
            .attr("type", "button")
            .attr("name", "Transform5")
            .attr("value", "Transform5")
            .on("click", function (d) {
                index = 0;
                transform = 5;
                page.selectAll("circle").remove();

                //var radius=document.getElementById("radius").value;
                //var amplitude=document.getElementById("Amplitude").value;
                page.selectAll("circle")
                    .data(dataVals)
                    .enter()
                    .append("circle")
                    .attr("cx", function (d, i) { return 300 + dist2 * Math.cos(d[0]); })
                    .attr("cy", function (d, i) { return 300 + dist2 * Math.sin(d[0]); })
                    .attr("r", width2)
                    .attr("id", function (d, i) { test = d[1]; return d[1]; })
                    .style("fill", function (d, i) { var fillingcolor; if (d[1] == "1") fillingcolor = "black"; else fillingcolor = "red"; return fillingcolor })
                    .on("click", clickCircle);

            });
        var button5 = d3.select("body")
            .append("input")
            .attr("type", "button")
            .attr("name", "Transform6")
            .attr("value", "Transform6")
            .on("click", function (d) {
                index = 0;
                transform = 6;
                page.selectAll("circle").remove();

                //var radius=document.getElementById("radius").value;
                //var amplitude=document.getElementById("Amplitude").value;
                page.selectAll("circle")
                    .data(dataVals)
                    .enter()
                    .append("circle")
                    .attr("cx", function (d, i) { return 300 + dist3 * Math.cos(d[0]); })
                    .attr("cy", function (d, i) { return 300 + dist3 * Math.sin(d[0]); })
                    .attr("r", width2)
                    .attr("id", function (d, i) { test = d[1]; return d[1]; })
                    .style("fill", function (d, i) { var fillingcolor; if (d[1] == "1") fillingcolor = "black"; else fillingcolor = "red"; return fillingcolor })
                    .on("click", clickCircle);

            });

        function handleMouseOver(d, i) {
            d3.select(this)
                .attr("stroke-width", 2)
                .attr("stroke", "black")
                .style("fill", "black");
            page.append("text").attr({})
        }

        function handleMouseOut(d, i) {
            d3.select(this).style("fill", "red");
        }

        function clickCircle() {
            //var index=0;
            if (index < 10) {
                var coordinates = [0, 0];
                d3.select(this).style("fill", "black");
                coordinates = d3.mouse(this);
                //time=Date.now();
                timeArry[index] = Date.now();
                var x = coordinates[0];
                var y = coordinates[1];
                xcoordinateArray[index] = x;
                ycoordinateArray[index] = y;
                //coordinateArray.push(coordinates);
                //console.log(coordinateArray);
                //document.write(coordinateArray);
            }
            index++;
            allcircles = page.selectAll("circle");
            allcircles.each(function (d, i) {
                var tempId = this.getAttribute("id");
                var indexId = index.toString();
                if (tempId == indexId)
                    this.style.fill = "black";
                else
                    this.style.fill = "red";
            }
            )
            //<input type="number" id="Amplitude" value=50 /><br>
        }
    </script>

    <table id="Distancedata"></table>


</body>

</html>

fitts/templates/fitts/fittstask1.html
<html>

<head>

    <script src="https://d3js.org/d3.v4.min.js"></script>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css">
    <meta charset="utf-8">
</head>

<body>

    <style>

    </style>
    <form id="frm" action="{% url 'fitts:fitts1' %}" method="POST" style="display: none;">
        {% csrf_token %}
        <input type="text" id="tfrm" name="transform">
        <input type="number" step="any" id="dt1" name="distance1">
        <input type="number" id="tm1" name="time1">
        <input type="number" step="any" id="dt2" name="distance2">
        <input type="number" id="tm2" name="time2">
        <input type="number" step="any" id="dt3" name="distance3">
        <input type="number" id="tm3" name="time3">
        <input type="number" step="any" id="dt4" name="distance4">
        <input type="number" id="tm4" name="time4">
        <input type="number" step="any" id="dt5" name="distance5">
        <input type="number" id="tm5" name="time5">
        <input type="number" step="any" id="dt6" name="distance6">
        <input type="number" id="tm6" name="time6">
        <input type="number" step="any" id="dt7" name="distance7">
        <input type="number" id="tm7" name="time7">
        <input type="number" step="any" id="dt8" name="distance8">
        <input type="number" id="tm8" name="time8">
        <input type="submit" id="sm">
    </form>
    <script>

        var transform = 1;
        var xcoordinateArray = [];
        var ycoordinateArray = [];
        var timeArry = [];
        var totalTime = [];
        var distance = [];
        var totalDistance = 0;
        var index = 0;
        var fillingColor;
        var dist = 100;
        var width = 25;
        var dist2 = 150;
        var dist3 = 200;
        var width2 = 30;
        var dataVals = [[0.698132, "1"], [1.39626, "8"], [2.0944, "6"], [2.79253, "4"], [3.49066, "2"], [4.18879, "9"], [4.88692, "7"], [5.58505, "5"], [6.28319, "3"]];

        var page = d3.select("body").append("svg");
        page.attr("width", 600).attr("height", 600)
            .style("border", "4px solid black");

        var circles = page.selectAll("circle")
            .data(dataVals)
            .enter()
            .append("circle");

        var circleGroup = circles.attr("cx", function (d, i) { return 300 + dist * Math.cos(d[0]); })
            .attr("cy", function (d, i) { return 300 + dist * Math.sin(d[0]); })
            .attr("r", width)
            .attr("id", function (d, i) { return d[1]; })
            //.on("mouseover",handleMouseOver)
            //.on("mouseout", handleMouseOut)
            .attr("stroke", "black")
            .style("fill", function (d, i) {
                if (d[1] == "1")
                    fillingColor = "black";
                else
                    fillingColor = "red";
                return fillingColor
            });

        circleGroup.on("click", clickCircle);

        var button = d3.select("body")
            .append("input")
            .attr("type", "button")
            .attr("name", "DistanceVsTime")
            .attr("value", "결과제출하기")
            .on("click", function (d) {
                for (var i = 1; i < 9; i++) {
                    var xSquare = (xcoordinateArray[i + 1] - xcoordinateArray[i]) * (xcoordinateArray[i + 1] - xcoordinateArray[i]);
                    var ySquare = (ycoordinateArray[i + 1] - ycoordinateArray[i]) * (ycoordinateArray[i + 1] - ycoordinateArray[i]);
                    distance[i] = Math.sqrt(xSquare + ySquare);
                    totalTime[i] = timeArry[i + 1] - timeArry[i];
                }
                for (var i = 1; i < 9; i++) {
                    totalDistance = +distance[i];
                }
                //document.getElementById("textBox").innerHTML=totalDistance;
                for (var i = 1; i < 10; i++) {
                    var tab = document.getElementById("Distancedata");
                    var row = tab.insertRow(0);
                    var cell1 = row.insertCell(0);
                    var cell2 = row.insertCell(1);

                    if (i == 9) {
                        cell1.innerHTML = "DistanceBetweenNodes";
                        cell2.innerHTML = "Time(in ms)";
                    }
                    else {
                        cell1.innerHTML = distance[i];
                        cell2.innerHTML = totalTime[i];
                        id_dt = "dt" + i
                        id_tm = "tm" + i
                        console.log(id_dt)
                        console.log(id_tm)
                        document.getElementById(id_dt).setAttribute('value', parseFloat(distance[i]));
                        document.getElementById(id_tm).setAttribute('value', parseFloat(totalTime[i]));
                        document.getElementById('tfrm').setAttribute('value', transform);
                        console.log(distance[i])
                        console.log(totalTime[i])
                        console.log(transform)
                    }
                }
                document.getElementById('sm').click();
            });

        function handleMouseOver(d, i) {
            d3.select(this)
                .attr("stroke-width", 2)
                .attr("stroke", "black")
                .style("fill", "black");
            page.append("text").attr({})
        }

        function handleMouseOut(d, i) {
            d3.select(this).style("fill", "red");
        }

        function clickCircle() {
            //var index=0;
            if (index < 10) {
                var coordinates = [0, 0];
                d3.select(this).style("fill", "black");
                coordinates = d3.mouse(this);
                //time=Date.now();
                timeArry[index] = Date.now();
                var x = coordinates[0];
                var y = coordinates[1];
                xcoordinateArray[index] = x;
                ycoordinateArray[index] = y;
                //coordinateArray.push(coordinates);
                //console.log(coordinateArray);
                //document.write(coordinateArray);
            }
            index++;
            allcircles = page.selectAll("circle");
            allcircles.each(function (d, i) {
                var tempId = this.getAttribute("id");
                var indexId = index.toString();
                if (tempId == indexId)
                    this.style.fill = "black";
                else
                    this.style.fill = "red";
            }
            )
            //<input type="number" id="Amplitude" value=50 /><br>
        }
    </script>

    <table id="Distancedata"></table>


</body>

</html>

fitts/templates/fitts/login.html
{% load static %}
<!doctype html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width">
</head>

<body>
    <form action="{% url 'fitts:login' %}" method="POST">
        {% csrf_token %}
        <input type="text" name="email" placeholder="이메일을 입력하세요">
        <input type="text" name="age" placeholder="나이를 입력하세요">
        <input type="submit" value="제출하고 실험 참여하기">
    </form>
    <img src="{% static 'fitts\guide.jpg' %}" style="width: 1000px; height: 600px; border: 1px;">
    </img>
    <!-- 
    <div class="container" id="container">
        <div class="form-container sign-in-container">
            <form action="#">
                <h1>Sign in</h1>
                <input type="email" placeholder="Email" />
                <input type="age" placeholder="Age" />
                <button>Sign In</button>
            </form>
        </div>
    </div> -->
</body>

</html>

whack_a_mole/game/templates/game/game.html
{% load static %}
<!doctype html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width">
  <title>두더지를 잡아라!</title>
  <link rel="stylesheet" href="{% static 'game/style.css' %}">
  <link href="https://fonts.googleapis.com/css?family=Press+Start+2P&display=swap" rel="stylesheet">
</head>

<body>
  <input type="text" id="mu" value={{mu}} style="display: none">
  <input type="text" id="pk" value={{pk}} style="display: none">
  <form action="{% url 'game:game' pk %}" method="POST" style="display: none">
    {% csrf_token %}
    <input type="text" id="score" name="score" value="0">
    <input type="submit" id="submit">
  </form>
  <div class="main">
    <div id="ending" class="ending">
      <p id="ending-box"></p>
      <button type="button" id="quit-ending"></p>
    </div>
    <div id="ending-bg" class="ending-bg"></div>

    <div class="whack-a-mole">
      <div id="molespace" class="mole">
        <img id="1" src="{% static 'game/mole.png' %}">
      </div>
    </div>

    <div class="point-box">
      <div class="point-wrap">
        <p id="point-text">점수 :</p>
        <p id="count-mole">0</p>
        <p id="remain-time">남은 시간 : </p>
        <p id="timer">30</p>
      </div>
      <div class="btn-wrap">
        <button type="button" class="start-btn">시작 버튼</button>
      </div>
    </div>
  </div>
  <script type="text/javascript" src="{% static 'game/mole.js' %}"></script>
</body>

</html>

whack_a_mole/game/templates/game/home.html
{% load static %}
<!doctype html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width">
    <title>두더지를 잡아라!</title>
    <link rel="stylesheet" href="{% static 'game/homestyle.css' %}">
</head>

<body>
    <form action="{% url 'game:home' %}" method="POST">
        {% csrf_token %}
        <select name="age" class="agebutton">
            <option value="ten">10대~20대</option>
            <option value="thirty">30대~40대</option>
            <option value="fifty">50대~60대</option>
        </select>
        <input type="submit" class="startbutton" value="게임 시작하기">
    </form>